theme: jekyll-theme-minimal
title: 'Advanced Topics in Single Cell RNA-Seq VDJ'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction and Lectures
  - title: Intro to the Workshop and Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Using Slack in this workshop
    url: base/slack
  - title: Using Zoom in this workshop
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex
  - title: Software and Links
    url: software_scripts/software
  - title: Scripts
    url: software_scripts/scripts_links

- heading: Prerequisites
  - title: CLI
    url: https://ucdavis-bioinformatics-training.github.io/2021-March-Introduction-to-the-Command-Line-for-Bioinformatics/
  - title: R
    url: https://ucdavis-bioinformatics-training.github.io/2021-March-Introduction-to-R-for-Bioinformatics/

  - heading: VDJ
  - title: Data Reduction
    url: VDJ/VDJ_reduction
  - title: Data Analysis
    url: VDJ/VDJ_analysis_fixed

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-March-Single-Cell-RNA-Seq-Analysis
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
